---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - page
  - gallery-page
- type: document
  path: src/_data/banner_message.json
  label: Banner Message
- type: document
  path: src/_data/shop_hours.json
  label: Shop Hours
- type: document
  path: src/_data/shop_closed_dates.json
  label: Shop Closed Dates
- type: document
  path: src/_data/non_delivery_dates.json
  label: Non Delivery Dates
- type: document
  path: src/_data/faq.json
  label: FAQ
- type: document
  path: src/_data/reviews.json
  label: Reviews
- type: document
  path: src/_data/photographers.json
  label: Photographers
upload_dir: ''
public_path: https://res.cloudinary.com/floriade/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: preview
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
