---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Misc
- type: document
  path: src/_data/photographers.json
  label: Photographers
- type: document
  path: src/_data/shop_categories.json
  label: Categories
- type: document
  path: src/_data/shop_category_names.json
  label: Category Names
  read_only: true
- type: directory
  path: src/blog
  label: Blog
  create: documents
  match: "**/*.md"
  templates:
  - blog-post
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*.{md,njk}"
  templates:
  - page
  - gallery-page
  - landing-page
  - simple-page
- type: directory
  path: src/products
  label: Products
  create: documents
  match: "**/*.{md,njk}"
  templates:
  - shop-product
- type: document
  path: src/_data/banner_message.json
  label: Banner Message
- type: document
  path: src/_data/shop_hours.json
  label: Shop Hours
- type: document
  path: src/_data/shop_closed_dates.json
  label: Shop Closed Dates
- type: document
  path: src/_data/non_delivery_dates.json
  label: Non Delivery Dates
- type: document
  path: src/_data/faq.json
  label: FAQ
- type: document
  path: src/_data/reviews.json
  label: Reviews
upload_dir: ''
public_path: https://res.cloudinary.com/floriade/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: preview
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
