name: Deploy Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }} >> .env
          echo INSTAGRAM_TOKEN=${{ secrets.INSTAGRAM_TOKEN }} >> .env
          echo STRIPE_TEST_PUBLIC_KEY=${{ secrets.STRIPE_TEST_PUBLIC_KEY }} >> .env
          echo STRIPE_LIVE_PUBLIC_KEY=${{ secrets.STRIPE_LIVE_PUBLIC_KEY }} >> .env
          echo RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }} >> .env
          echo RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} >> .env
          echo GOOGLE_PLACE_ID=${{ secrets.GOOGLE_PLACE_ID }} >> .env
          echo GOOGLE_MAPS_KEY=${{ secrets.GOOGLE_MAPS_KEY }} >> .env
          mkdir fake
          cp .env fake/env

      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: floriade.co.nz
          # ftp username
          username: ${{ secrets.FTP_USER }}
          # ftp password
          password: ${{ secrets.FTP_PASS }}
          # Server port to connect to (read your web hosts docs)
          port: # optional
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: # optional
          # Folder to upload from, must end with trailing slash /
          local-dir: ./fake/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: public_html/eleventy/
          # Path and name of the state file - this file is used to track which files have been deployed
          state-name: # optional
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          dry-run: # optional
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          dangerous-clean-slate: # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          exclude: # optional
          # How verbose should the information be - warn, info, debug
          log-level: # optional
          # strict or loose
          security: # optional
